### ISSUE TITLE
Logstash shuts down after a few seconds of running

### ISSUE THREAD

**Issue by djangofan** [Haris3243/docker-elkstack#1]
Hi, I was trying your project and using stack version 7.9.3 (or the one you specified; same result)   and after logstash starts, it shuts down soon after.   I am on a Mac.  Any idea why this is happening?

```
[2020-11-05T16:41:59,368][INFO ][logstash.agent ] Successfully started Logstash API endpoint {:port=>9600}
[2020-11-05T16:42:00,219][INFO ][logstash.javapipeline ][.monitoring-logstash] Pipeline terminated
   {"pipeline.id"=>".monitoring-logstash"}
[2020-11-05T16:42:01,285][INFO ][logstash.runner ] Logstash shut down.
```

**Comment by djangofan** [comment]
I found some comments on Google about this but none of the ideas I found worked for me.   I think this is a common issue people run into with the logstash container and so I suspect there is an easy solution.

**Comment by Haris3243** [comment]
> Hi, I was trying your project and using stack version 7.9.3 (or the one you specified; same result) and after logstash starts, it shuts down soon after. I am on a Mac. Any idea why this is happening?
> 
> ```
> [2020-11-05T16:41:59,368][INFO ][logstash.agent ] Successfully started Logstash API endpoint {:port=>9600}
> [2020-11-05T16:42:00,219][INFO ][logstash.javapipeline ][.monitoring-logstash] Pipeline terminated
>    {"pipeline.id"=>".monitoring-logstash"}
> [2020-11-05T16:42:01,285][INFO ][logstash.runner ] Logstash shut down.
> ```

@djangofan  Probably it is due to volume mapping which is defined in the yml file, it is according to my windows environment. please change path according to your environment and let me know if it resolves your issue or not. 
change .\logstash in the following w.r.t your mac environment
 volumes:
          - .\logstash:/usr/share/logstash/pipeline/
